export enum ComplaintType {
  ACADEMIC = "ACADEMIC",
  BEHAVIORAL = "BEHAVIORAL",
  FACILITY = "FACILITY",
  SAFETY = "SAFETY",
  BULLYING = "BULLYING",
  DISCIPLINARY = "DISCIPLINARY",
  FINANCIAL = "FINANCIAL",
  ADMINISTRATIVE = "ADMINISTRATIVE",
  OTHER = "OTHER",
}
