/**
 * Audit Action Enum
 * Defines the types of actions that can be audited in the system
 */
export enum AuditAction {
  // CRUD Operations
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  EXECUTE = "EXECUTE",

  // Authentication Actions
  LOGIN = "LOGIN",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  PASSWORD_RESET = "PASSWORD_RESET",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",

  // Authorization Actions
  UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  ROLE_CHANGE = "ROLE_CHANGE",

  // Security Actions
  SECURITY_VIOLATION = "SECURITY_VIOLATION",
  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  SESSION_EXPIRED = "SESSION_EXPIRED",

  // System Actions
  ERROR_OCCURRED = "ERROR_OCCURRED",
  SYSTEM_BACKUP = "SYSTEM_BACKUP",
  SYSTEM_RESTORE = "SYSTEM_RESTORE",
  CONFIGURATION_CHANGE = "CONFIGURATION_CHANGE",

  // Data Actions
  DATA_EXPORT = "DATA_EXPORT",
  DATA_IMPORT = "DATA_IMPORT",
  BULK_OPERATION = "BULK_OPERATION",

  // File Actions
  FILE_UPLOAD = "FILE_UPLOAD",
  FILE_DOWNLOAD = "FILE_DOWNLOAD",
  FILE_DELETE = "FILE_DELETE",
}
