export enum LeaveRequestStatus {
  PENDING_PARENT_APPROVAL = 'PENDING_PARENT_APPROVAL',
  PENDING_TEACHER_APPROVAL = 'PENDING_TEACHER_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
