export enum TeacherLeaveRequestType {
  SICK = 'SICK',
  PERSONAL = 'PERSONAL',
  VACATION = 'VACATION',
  EMERGENCY = 'EMERGENCY',
  MEDICAL = 'MEDICAL',
  FAMILY = 'FAMILY',
  PROFESSIONAL_DEVELOPMENT = 'PROFESSIONAL_DEVELOPMENT',
  CONFERENCE = 'CONFERENCE',
  WORKSHOP = 'WORKSHOP',
  OTHER = 'OTHER',
}
