export interface DatabaseField {
  name: string;
  label: string;
  type: 'string' | 'number' | 'date' | 'boolean' | 'image' | 'json';
  table: string;
  required?: boolean;
  maxLength?: number;
  format?: string;
  description?: string;
}

export interface UserTypeFields {
  [key: string]: DatabaseField[];
}

export const DATABASE_FIELDS: UserTypeFields = {
  student: [
    {
      name: 'fullName',
      label: 'Full Name',
      type: 'string',
      table: 'user',
      required: true,
    },
    { name: 'firstName', label: 'First Name', type: 'string', table: 'user' },
    { name: 'lastName', label: 'Last Name', type: 'string', table: 'user' },
    { name: 'email', label: 'Email', type: 'string', table: 'user' },
    { name: 'phone', label: 'Phone', type: 'string', table: 'user' },
    {
      name: 'rollNumber',
      label: 'Roll Number',
      type: 'string',
      table: 'student',
      required: true,
    },
    {
      name: 'studentId',
      label: 'Student ID',
      type: 'string',
      table: 'student',
    },
    {
      name: 'admissionDate',
      label: 'Admission Date',
      type: 'date',
      table: 'student',
      format: 'YYYY-MM-DD',
    },
    {
      name: 'dateOfBirth',
      label: 'Date of Birth',
      type: 'date',
      table: 'student',
      format: 'YYYY-MM-DD',
    },
    {
      name: 'dob',
      label: 'DOB',
      type: 'date',
      table: 'student',
      format: 'DD/MM/YYYY',
    },
    { name: 'gender', label: 'Gender', type: 'string', table: 'student' },
    {
      name: 'bloodGroup',
      label: 'Blood Group',
      type: 'string',
      table: 'student',
    },
    { name: 'ethnicity', label: 'Ethnicity', type: 'string', table: 'student' },
    { name: 'address', label: 'Address', type: 'string', table: 'student' },
    { name: 'city', label: 'City', type: 'string', table: 'student' },
    { name: 'state', label: 'State', type: 'string', table: 'student' },
    { name: 'pinCode', label: 'PIN Code', type: 'string', table: 'student' },
    {
      name: 'fatherName',
      label: 'Father Name',
      type: 'string',
      table: 'student',
    },
    {
      name: 'motherName',
      label: 'Mother Name',
      type: 'string',
      table: 'student',
    },
    {
      name: 'fatherPhone',
      label: 'Father Phone',
      type: 'string',
      table: 'student',
    },
    {
      name: 'motherPhone',
      label: 'Mother Phone',
      type: 'string',
      table: 'student',
    },
    {
      name: 'emergencyContact',
      label: 'Emergency Contact',
      type: 'string',
      table: 'student',
    },
    {
      name: 'academicStatus',
      label: 'Academic Status',
      type: 'string',
      table: 'student',
    },
    {
      name: 'feeStatus',
      label: 'Fee Status',
      type: 'string',
      table: 'student',
    },
    {
      name: 'profilePhotoUrl',
      label: 'Profile Photo',
      type: 'image',
      table: 'student',
    },
    { name: 'imageUrl', label: 'Photo', type: 'image', table: 'student' },
    { name: 'class.name', label: 'Class Name', type: 'string', table: 'class' },
    { name: 'class.grade', label: 'Grade', type: 'number', table: 'class' },
    { name: 'class.section', label: 'Section', type: 'string', table: 'class' },
    { name: 'class.shift', label: 'Shift', type: 'string', table: 'class' },
    {
      name: 'class.academicYear',
      label: 'Academic Year',
      type: 'string',
      table: 'class',
    },
  ],
  teacher: [
    {
      name: 'fullName',
      label: 'Full Name',
      type: 'string',
      table: 'user',
      required: true,
    },
    { name: 'firstName', label: 'First Name', type: 'string', table: 'user' },
    { name: 'lastName', label: 'Last Name', type: 'string', table: 'user' },
    { name: 'email', label: 'Email', type: 'string', table: 'user' },
    { name: 'phone', label: 'Phone', type: 'string', table: 'user' },
    {
      name: 'employeeId',
      label: 'Employee ID',
      type: 'string',
      table: 'teacher',
      required: true,
    },
    {
      name: 'joiningDate',
      label: 'Joining Date',
      type: 'date',
      table: 'teacher',
      format: 'YYYY-MM-DD',
    },
    {
      name: 'dateOfBirth',
      label: 'Date of Birth',
      type: 'date',
      table: 'teacher',
      format: 'YYYY-MM-DD',
    },
    {
      name: 'dob',
      label: 'DOB',
      type: 'date',
      table: 'teacher',
      format: 'DD/MM/YYYY',
    },
    { name: 'gender', label: 'Gender', type: 'string', table: 'teacher' },
    {
      name: 'bloodGroup',
      label: 'Blood Group',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'maritalStatus',
      label: 'Marital Status',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'designation',
      label: 'Designation',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'department',
      label: 'Department',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'specialization',
      label: 'Specialization',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'qualification',
      label: 'Qualification',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'experienceYears',
      label: 'Experience (Years)',
      type: 'number',
      table: 'teacher',
    },
    {
      name: 'certifications',
      label: 'Certifications',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'languagesKnown',
      label: 'Languages Known',
      type: 'json',
      table: 'teacher',
    },
    {
      name: 'isClassTeacher',
      label: 'Class Teacher',
      type: 'boolean',
      table: 'teacher',
    },
    {
      name: 'basicSalary',
      label: 'Basic Salary',
      type: 'number',
      table: 'teacher',
    },
    {
      name: 'totalSalary',
      label: 'Total Salary',
      type: 'number',
      table: 'teacher',
    },
    {
      name: 'bankAccountNumber',
      label: 'Bank Account',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'citizenshipNumber',
      label: 'Citizenship Number',
      type: 'string',
      table: 'teacher',
    },
    {
      name: 'panNumber',
      label: 'PAN Number',
      type: 'string',
      table: 'teacher',
    },
    { name: 'imageUrl', label: 'Photo', type: 'image', table: 'teacher' },
    { name: 'address', label: 'Address', type: 'string', table: 'teacher' },
    {
      name: 'employmentStatus',
      label: 'Employment Status',
      type: 'string',
      table: 'teacher',
    },
  ],
  staff: [
    {
      name: 'fullName',
      label: 'Full Name',
      type: 'string',
      table: 'user',
      required: true,
    },
    { name: 'firstName', label: 'First Name', type: 'string', table: 'user' },
    { name: 'lastName', label: 'Last Name', type: 'string', table: 'user' },
    { name: 'email', label: 'Email', type: 'string', table: 'user' },
    { name: 'phone', label: 'Phone', type: 'string', table: 'user' },
    {
      name: 'employeeId',
      label: 'Employee ID',
      type: 'string',
      table: 'staff',
      required: true,
    },
    {
      name: 'joiningDate',
      label: 'Joining Date',
      type: 'date',
      table: 'staff',
      format: 'YYYY-MM-DD',
    },
    {
      name: 'employmentDate',
      label: 'Employment Date',
      type: 'date',
      table: 'staff',
      format: 'YYYY-MM-DD',
    },
    {
      name: 'dob',
      label: 'Date of Birth',
      type: 'date',
      table: 'staff',
      format: 'YYYY-MM-DD',
    },
    { name: 'gender', label: 'Gender', type: 'string', table: 'staff' },
    {
      name: 'bloodGroup',
      label: 'Blood Group',
      type: 'string',
      table: 'staff',
    },
    {
      name: 'maritalStatus',
      label: 'Marital Status',
      type: 'string',
      table: 'staff',
    },
    {
      name: 'designation',
      label: 'Designation',
      type: 'string',
      table: 'staff',
    },
    { name: 'department', label: 'Department', type: 'string', table: 'staff' },
    {
      name: 'experienceYears',
      label: 'Experience (Years)',
      type: 'number',
      table: 'staff',
    },
    {
      name: 'basicSalary',
      label: 'Basic Salary',
      type: 'number',
      table: 'staff',
    },
    {
      name: 'totalSalary',
      label: 'Total Salary',
      type: 'number',
      table: 'staff',
    },
    { name: 'allowances', label: 'Allowances', type: 'number', table: 'staff' },
    {
      name: 'bankAccountNumber',
      label: 'Bank Account',
      type: 'string',
      table: 'staff',
    },
    { name: 'bankName', label: 'Bank Name', type: 'string', table: 'staff' },
    {
      name: 'bankBranch',
      label: 'Bank Branch',
      type: 'string',
      table: 'staff',
    },
    {
      name: 'citizenshipNumber',
      label: 'Citizenship Number',
      type: 'string',
      table: 'staff',
    },
    { name: 'panNumber', label: 'PAN Number', type: 'string', table: 'staff' },
    {
      name: 'emergencyContact',
      label: 'Emergency Contact',
      type: 'string',
      table: 'staff',
    },
    {
      name: 'employmentStatus',
      label: 'Employment Status',
      type: 'string',
      table: 'staff',
    },
    { name: 'permissions', label: 'Permissions', type: 'json', table: 'staff' },
  ],
  visitor: [
    {
      name: 'fullName',
      label: 'Full Name',
      type: 'string',
      table: 'user',
      required: true,
    },
    { name: 'firstName', label: 'First Name', type: 'string', table: 'user' },
    { name: 'lastName', label: 'Last Name', type: 'string', table: 'user' },
    { name: 'email', label: 'Email', type: 'string', table: 'user' },
    { name: 'phone', label: 'Phone', type: 'string', table: 'user' },
    {
      name: 'company',
      label: 'Company/Organization',
      type: 'string',
      table: 'visitor',
    },
    {
      name: 'purpose',
      label: 'Purpose of Visit',
      type: 'string',
      table: 'visitor',
    },
    {
      name: 'contactPerson',
      label: 'Contact Person',
      type: 'string',
      table: 'visitor',
    },
    {
      name: 'validUntil',
      label: 'Valid Until',
      type: 'date',
      table: 'visitor',
      format: 'DD/MM/YYYY',
    },
    {
      name: 'entryTime',
      label: 'Entry Time',
      type: 'date',
      table: 'visitor',
      format: 'HH:mm',
    },
    {
      name: 'exitTime',
      label: 'Exit Time',
      type: 'date',
      table: 'visitor',
      format: 'HH:mm',
    },
    {
      name: 'visitDate',
      label: 'Visit Date',
      type: 'date',
      table: 'visitor',
      format: 'DD/MM/YYYY',
    },
    { name: 'idType', label: 'ID Type', type: 'string', table: 'visitor' },
    { name: 'idNumber', label: 'ID Number', type: 'string', table: 'visitor' },
    {
      name: 'vehicleNumber',
      label: 'Vehicle Number',
      type: 'string',
      table: 'visitor',
    },
    {
      name: 'escortRequired',
      label: 'Escort Required',
      type: 'boolean',
      table: 'visitor',
    },
    { name: 'status', label: 'Status', type: 'string', table: 'visitor' },
    {
      name: 'profilePhotoUrl',
      label: 'Photo',
      type: 'image',
      table: 'visitor',
    },
  ],
  guest: [
    {
      name: 'fullName',
      label: 'Full Name',
      type: 'string',
      table: 'user',
      required: true,
    },
    { name: 'firstName', label: 'First Name', type: 'string', table: 'user' },
    { name: 'lastName', label: 'Last Name', type: 'string', table: 'user' },
    { name: 'email', label: 'Email', type: 'string', table: 'user' },
    { name: 'phone', label: 'Phone', type: 'string', table: 'user' },
    {
      name: 'organization',
      label: 'Organization',
      type: 'string',
      table: 'guest',
    },
    {
      name: 'designation',
      label: 'Designation',
      type: 'string',
      table: 'guest',
    },
    { name: 'purpose', label: 'Purpose', type: 'string', table: 'guest' },
    {
      name: 'validFrom',
      label: 'Valid From',
      type: 'date',
      table: 'guest',
      format: 'DD/MM/YYYY',
    },
    {
      name: 'validUntil',
      label: 'Valid Until',
      type: 'date',
      table: 'guest',
      format: 'DD/MM/YYYY',
    },
    {
      name: 'accessLevel',
      label: 'Access Level',
      type: 'string',
      table: 'guest',
    },
    {
      name: 'sponsoredBy',
      label: 'Sponsored By',
      type: 'string',
      table: 'guest',
    },
    { name: 'eventName', label: 'Event Name', type: 'string', table: 'guest' },
    { name: 'profilePhotoUrl', label: 'Photo', type: 'image', table: 'guest' },
  ],
};

export const getFieldsForUserType = (userType: string): DatabaseField[] => {
  return DATABASE_FIELDS[userType.toLowerCase()] || [];
};

export const validateFieldMapping = (
  userType: string,
  fieldName: string,
): boolean => {
  const fields = getFieldsForUserType(userType);
  return fields.some(field => field.name === fieldName);
};
