export const MOTHER_TONGUE_OPTIONS: Array<{ value: string; label: string }> = [
  { value: 'NEPALI', label: 'Nepali' },
  { value: 'MAITHILI', label: 'Maithili' },
  { value: 'BHOJPURI', label: 'Bhojpuri' },
  { value: 'THARU', label: 'Tharu' },
  { value: 'TAMANG', label: 'Tamang' },
  { value: 'BAJJIKA', label: 'Bajjika' },
  { value: 'AVADHI', label: 'Avadhi' },
  { value: 'NEPALBHASHA_NEWARI', label: 'Nepalbhasha (Newari)' },
  { value: 'MAGAR_DHUT', label: 'Magar Dhut' },
  { value: 'DOTELI', label: 'Doteli' },
  { value: 'URDU', label: 'Urdu' },
  { value: 'YAKTHUNG_LIMBU', label: 'Yakthung/ Limbu' },
  { value: 'GURUNG', label: 'Gurung' },
  { value: 'MAGAHI', label: 'Magahi' },
  { value: 'BAITADELI', label: 'Baitadeli' },
  { value: 'RAI', label: 'Rai' },
  { value: 'ACHHAMI', label: 'Achhami' },
  { value: 'BANTAWA', label: 'Bantawa' },
  { value: 'RAJBANSHI', label: 'Rajbanshi' },
  { value: 'SHERPA', label: 'Sherpa' },
  { value: 'KHASH', label: 'Khash' },
  { value: 'BAJHANGI', label: 'Bajhangi' },
  { value: 'HINDI', label: 'Hindi' },
  { value: 'MAGAR_KHAM', label: 'Magar Kham' },
  { value: 'CHAMLING', label: 'Chamling' },
  { value: 'RANATHARU', label: 'Ranatharu' },
  { value: 'CHEPANG', label: 'Chepang' },
  { value: 'BAJURELI', label: 'Bajureli' },
  { value: 'SANTHALI', label: 'Santhali' },
  { value: 'DANUWAR', label: 'Danuwar' },
  { value: 'DARCHULELI', label: 'Darchuleli' },
  { value: 'URANW_URAU', label: 'Uranw/Urau' },
  { value: 'KULUNG', label: 'Kulung' },
  { value: 'ANGIKA', label: 'Angika' },
  { value: 'MAJHI', label: 'Majhi' },
  { value: 'SUNUWAR', label: 'Sunuwar' },
  { value: 'THAMI', label: 'Thami' },
  { value: 'GANAGAI', label: 'Ganagai' },
  { value: 'THULUNG', label: 'Thulung' },
  { value: 'BANGLA', label: 'Bangla' },
  { value: 'GHALE', label: 'Ghale' },
  { value: 'SAMPANG', label: 'Sampang' },
  { value: 'MARWADI', label: 'Marwadi' },
  { value: 'DADELDHURI', label: 'Dadeldhuri' },
  { value: 'DHIMAL', label: 'Dhimal' },
  { value: 'TAJPURIYA', label: 'Tajpuriya' },
  { value: 'KUMAL', label: 'Kumal' },
  { value: 'KHALING', label: 'Khaling' },
  { value: 'MUSALMAN', label: 'Musalman' },
  { value: 'WAMBULE', label: 'Wambule' },
  { value: 'BAHING_BAYUNG', label: 'Bahing/ Bayung' },
  { value: 'YAKKHA', label: 'Yakkha' },
  { value: 'SANSKRIT', label: 'Sanskrit' },
  { value: 'BHUJEL', label: 'Bhujel' },
  { value: 'BHOTE', label: 'Bhote' },
  { value: 'DARAI', label: 'Darai' },
  { value: 'YAMPHU_YAMPHE', label: 'Yamphu/Yamphe' },
  { value: 'NACHHIRING', label: 'Nachhiring' },
  { value: 'HYOLMO_YHOLMO', label: 'Hyolmo/Yholmo' },
  { value: 'DUMI', label: 'Dumi' },
  { value: 'JUMLI', label: 'Jumli' },
  { value: 'BOTE', label: 'Bote' },
  { value: 'MEWAHANG', label: 'Mewahang' },
  { value: 'PUMA', label: 'Puma' },
  { value: 'PAHARI', label: 'Pahari' },
  { value: 'ATHPAHARIYA', label: 'Athpahariya' },
  { value: 'DUNGMALI', label: 'Dungmali' },
  { value: 'JIREL', label: 'Jirel' },
  { value: 'TIBETAN', label: 'Tibetan' },
  { value: 'DAILEKHI', label: 'Dailekhi' },
  { value: 'CHUM_NUBRI', label: 'Chum/ Nubri' },
  { value: 'CHHANTYAL', label: 'Chhantyal' },
  { value: 'RAJI', label: 'Raji' },
  { value: 'THAKALI', label: 'Thakali' },
  { value: 'MECHE', label: 'Meche' },
  { value: 'KOYEE', label: 'Koyee' },
  { value: 'LOHORUNG', label: 'Lohorung' },
  { value: 'KEWARAT', label: 'Kewarat' },
  { value: 'DOLPALI', label: 'Dolpali' },
  { value: 'DONE', label: 'Done' },
  { value: 'MUGALI', label: 'Mugali' },
  { value: 'JERO_JERUNG', label: 'Jero/ Jerung' },
  { value: 'KARMARONG', label: 'Karmarong' },
  { value: 'CHHINTANG', label: 'Chhintang' },
  { value: 'LHOPA', label: 'Lhopa' },
  { value: 'LAPCHA', label: 'Lapcha' },
  { value: 'MUNDA_MUDIYARI', label: 'Munda/Mudiyari' },
  { value: 'MANANGE', label: 'Manange' },
  { value: 'CHHILING', label: 'Chhiling' },
  { value: 'DURA', label: 'Dura' },
  { value: 'TILUNG', label: 'Tilung' },
  { value: 'SIGN_LANGUAGE', label: 'Sign Language' },
  { value: 'BYANSI', label: 'Byansi' },
  { value: 'BALKURA_BARAM', label: 'Balkura/ Baram' },
  { value: 'BARAGUNWA', label: 'Baragunwa' },
  { value: 'SADRI', label: 'Sadri' },
  { value: 'ENGLISH', label: 'English' },
  { value: 'MAGAR_KAIKE', label: 'Magar Kaike' },
  { value: 'SONAHA', label: 'Sonaha' },
  { value: 'HAYU_VAYU', label: 'Hayu/ Vayu' },
  { value: 'KISAN', label: 'Kisan' },
  { value: 'PUNJABI', label: 'Punjabi' },
  { value: 'DHULELI', label: 'Dhuleli' },
  { value: 'KHAMCHI_RAUTE', label: 'Khamchi (Raute)' },
  { value: 'LUNGKHIM', label: 'Lungkhim' },
  { value: 'LOWA', label: 'Lowa' },
  { value: 'KAGATE', label: 'Kagate' },
  { value: 'WALING_WALUNG', label: 'Waling/ Walung' },
  { value: 'NAR_PHU', label: 'Nar-Phu' },
  { value: 'LHOMI', label: 'Lhomi' },
  { value: 'TICHHURONG_POIKE', label: 'Tichhurong Poike' },
  { value: 'KURMALI', label: 'Kurmali' },
  { value: 'KOCHE', label: 'Koche' },
  { value: 'SINDHI', label: 'Sindhi' },
  { value: 'PHANGDUWALI', label: 'Phangduwali' },
  { value: 'BELHARE', label: 'Belhare' },
  { value: 'SUREL', label: 'Surel' },
  { value: 'MALPANDE', label: 'Malpande' },
  { value: 'KHARIYA', label: 'Khariya' },
  { value: 'SADHANI', label: 'Sadhani' },
  { value: 'HARIYANWI', label: 'Hariyanwi' },
  { value: 'SAM', label: 'Sam' },
  { value: 'BANKARIYA', label: 'Bankariya' },
  { value: 'KUSUNDA', label: 'Kusunda' },
];

export const DISABILITY_TYPE_OPTIONS: Array<{
  value: string;
  label: string;
}> = [
  { value: 'NO_DISABILITY', label: 'No Disability' },
  { value: 'PHYSICAL', label: 'Physical' },
  { value: 'INTELLECTUAL_DISABILITY', label: 'Intellectual Disability' },
  { value: 'DEAF', label: 'Deaf' },
  { value: 'HARD_OF_HEARING', label: 'Hard of Hearing' },
  { value: 'TOTALLY_BLIND', label: 'Totally Blind' },
  { value: 'VISUALLY_IMPAIRED', label: 'Visually Impaired' },
  { value: 'LOW_VISION', label: 'Low Vision' },
  { value: 'DEAFBLINDNESS', label: 'Deafblindness' },
  { value: 'BLIND', label: 'Blind' },
  { value: 'VOCAL_AND_SPEECH_RELATED', label: 'Vocal and Speech related' },
  { value: 'AUTISM', label: 'Autism' },
  { value: 'MENTAL_PSYCHOSOCIAL', label: 'Mental / Psychosocial' },
  { value: 'HEMOPHILIA', label: 'Hemophilia' },
  { value: 'MULTIPLE_DISABILITY', label: 'Multiple Disability' },
  { value: 'DEAF_AND_BLIND', label: 'Deaf and Blind' },
  { value: 'NA', label: 'N/A' },
];

export const formatMotherTongue = (value?: string): string => {
  if (!value) return 'N/A';
  return (
    MOTHER_TONGUE_OPTIONS.find(option => option.value === value)?.label || value
  );
};

export const formatDisabilityType = (value?: string): string => {
  if (!value) return 'N/A';
  return (
    DISABILITY_TYPE_OPTIONS.find(option => option.value === value)?.label ||
    value
  );
};
