// Mock data for timetable viewer
export const mockStore = {
  selectedGrade: 'Grade 10' as const,
  selectedSection: 'A' as const,
  currentWeek: new Date('2025-01-27'),
  viewMode: 'week' as const,
};

export const mockQuery = {
  timetableData: {
    classId: 'class-1',
    sectionId: 'section-1',
    grade: 'Grade 10',
    section: 'A',
    classTeacher: {
      id: 'teacher-1',
      firstName: 'Emma',
      lastName: 'Thompson',
      employeeId: '35/40',
    },
    room: '108',
    weeklyHours: 42,
    totalSubjects: 8,
    lastUpdated: new Date('2025-01-28'),
    schedule: [
      {
        timeSlot: '8:00 - 8:50',
        periods: {
          monday: {
            id: 'period-1',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
          tuesday: {
            id: 'period-2',
            subject: 'English Literature',
            teacher: { firstName: 'Mr.', lastName: 'Thompson' },
            room: '102',
            type: 'regular' as const,
          },
          wednesday: {
            id: 'period-3',
            subject: 'Physics',
            teacher: { firstName: 'Mr.', lastName: 'Chen' },
            room: '203',
            type: 'regular' as const,
          },
          thursday: {
            id: 'period-4',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
          friday: {
            id: 'period-5',
            subject: 'Chemistry',
            teacher: { firstName: 'Mr.', lastName: 'Wilson' },
            room: '204',
            type: 'regular' as const,
          },
          saturday: {
            id: 'period-6',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
        },
      },
      {
        timeSlot: '8:50 - 9:40',
        periods: {
          monday: {
            id: 'period-7',
            subject: 'Physics',
            teacher: { firstName: 'Mr.', lastName: 'Chen' },
            room: '203',
            type: 'regular' as const,
          },
          tuesday: {
            id: 'period-8',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
          wednesday: {
            id: 'period-9',
            subject: 'Biology',
            teacher: { firstName: 'Ms.', lastName: 'Garcia' },
            room: '301',
            type: 'regular' as const,
          },
          thursday: {
            id: 'period-10',
            subject: 'World History',
            teacher: { firstName: 'Mr.', lastName: 'Rodriguez' },
            room: '102',
            type: 'regular' as const,
          },
          friday: {
            id: 'period-11',
            subject: 'Geography',
            teacher: { firstName: 'Ms.', lastName: 'Brown' },
            room: '204',
            type: 'regular' as const,
          },
          saturday: {
            id: 'period-12',
            subject: 'Science Lab',
            teacher: { firstName: 'Mr.', lastName: 'Chen' },
            room: '301',
            type: 'regular' as const,
          },
        },
      },
      {
        timeSlot: '9:40 - 10:00',
        periods: {
          monday: {
            id: 'break-1',
            subject: 'Morning Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'break' as const,
          },
          tuesday: {
            id: 'break-2',
            subject: 'Morning Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'break' as const,
          },
          wednesday: {
            id: 'break-3',
            subject: 'Morning Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'break' as const,
          },
          thursday: {
            id: 'break-4',
            subject: 'Morning Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'break' as const,
          },
          friday: {
            id: 'break-5',
            subject: 'Morning Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'break' as const,
          },
          saturday: {
            id: 'break-6',
            subject: 'Morning Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'break' as const,
          },
        },
      },
      {
        timeSlot: '10:00 - 10:50',
        periods: {
          monday: {
            id: 'period-13',
            subject: 'English Literature',
            teacher: { firstName: 'Mr.', lastName: 'Thompson' },
            room: '102',
            type: 'regular' as const,
          },
          tuesday: {
            id: 'period-14',
            subject: 'Chemistry',
            teacher: { firstName: 'Mr.', lastName: 'Wilson' },
            room: '204',
            type: 'regular' as const,
          },
          wednesday: {
            id: 'period-15',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
          thursday: {
            id: 'period-16',
            subject: 'English Literature',
            teacher: { firstName: 'Mr.', lastName: 'Thompson' },
            room: '102',
            type: 'regular' as const,
          },
          friday: {
            id: 'period-17',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
          saturday: {
            id: 'period-18',
            subject: 'Sports Activity',
            teacher: { firstName: 'Mr.', lastName: 'Smith' },
            room: 'Sports Ground',
            type: 'activity' as const,
          },
        },
      },
      {
        timeSlot: '10:50 - 11:40',
        periods: {
          monday: {
            id: 'period-19',
            subject: 'Chemistry',
            teacher: { firstName: 'Mr.', lastName: 'Wilson' },
            room: '204',
            type: 'regular' as const,
          },
          tuesday: {
            id: 'period-20',
            subject: 'Physics',
            teacher: { firstName: 'Mr.', lastName: 'Chen' },
            room: '203',
            type: 'regular' as const,
          },
          wednesday: {
            id: 'period-21',
            subject: 'Computer Science',
            teacher: { firstName: 'Ms.', lastName: 'Lee' },
            room: 'Computer Lab',
            type: 'regular' as const,
          },
          thursday: {
            id: 'period-22',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
          friday: {
            id: 'period-23',
            subject: 'Project Work',
            teacher: { firstName: 'Ms.', lastName: 'Garcia' },
            room: '301',
            type: 'study_hall' as const,
          },
          saturday: {
            id: 'period-24',
            subject: 'Mathematics',
            teacher: { firstName: 'Ms.', lastName: 'Mitchell' },
            room: '201',
            type: 'regular' as const,
          },
        },
      },
      {
        timeSlot: '11:40 - 12:30',
        periods: {
          monday: {
            id: 'period-25',
            subject: 'Biology',
            teacher: { firstName: 'Ms.', lastName: 'Garcia' },
            room: '301',
            type: 'regular' as const,
          },
          tuesday: {
            id: 'period-26',
            subject: 'World History',
            teacher: { firstName: 'Mr.', lastName: 'Rodriguez' },
            room: '102',
            type: 'regular' as const,
          },
          wednesday: {
            id: 'period-27',
            subject: 'Geography',
            teacher: { firstName: 'Ms.', lastName: 'Brown' },
            room: '204',
            type: 'regular' as const,
          },
          thursday: {
            id: 'period-28',
            subject: 'English Literature',
            teacher: { firstName: 'Mr.', lastName: 'Thompson' },
            room: '102',
            type: 'regular' as const,
          },
          friday: {
            id: 'period-29',
            subject: 'Physical Education',
            teacher: { firstName: 'Mr.', lastName: 'Smith' },
            room: 'Sports Ground',
            type: 'activity' as const,
          },
          saturday: {
            id: 'period-30',
            subject: 'Study Hall',
            teacher: { firstName: 'Ms.', lastName: 'Anderson' },
            room: 'Library',
            type: 'study_hall' as const,
          },
        },
      },
      {
        timeSlot: '12:30 - 1:20',
        periods: {
          monday: {
            id: 'lunch-1',
            subject: 'Lunch Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'lunch' as const,
          },
          tuesday: {
            id: 'lunch-2',
            subject: 'Lunch Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'lunch' as const,
          },
          wednesday: {
            id: 'lunch-3',
            subject: 'Lunch Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'lunch' as const,
          },
          thursday: {
            id: 'lunch-4',
            subject: 'Lunch Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'lunch' as const,
          },
          friday: {
            id: 'lunch-5',
            subject: 'Lunch Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'lunch' as const,
          },
          saturday: {
            id: 'lunch-6',
            subject: 'Lunch Break',
            teacher: { firstName: '', lastName: 'Cafeteria' },
            room: 'Cafeteria',
            type: 'lunch' as const,
          },
        },
      },
      {
        timeSlot: '1:20 - 2:10',
        periods: {
          monday: {
            id: 'period-31',
            subject: 'Physical Education',
            teacher: { firstName: 'Mr.', lastName: 'Smith' },
            room: 'Sports Ground',
            type: 'activity' as const,
          },
          tuesday: {
            id: 'period-32',
            subject: 'Chemistry',
            teacher: { firstName: 'Mr.', lastName: 'Wilson' },
            room: 'Lab 102',
            type: 'regular' as const,
          },
          wednesday: {
            id: 'period-33',
            subject: 'Physics',
            teacher: { firstName: 'Mr.', lastName: 'Chen' },
            room: 'Lab 101',
            type: 'regular' as const,
          },
          thursday: {
            id: 'period-34',
            subject: 'Physics',
            teacher: { firstName: 'Mr.', lastName: 'Chen' },
            room: '203',
            type: 'regular' as const,
          },
          friday: {
            id: 'period-35',
            subject: 'Fine Arts',
            teacher: { firstName: 'Ms.', lastName: 'Park' },
            room: 'Art Studio',
            type: 'activity' as const,
          },
          saturday: {
            id: 'period-36',
            subject: 'Fine Arts',
            teacher: { firstName: 'Ms.', lastName: 'Park' },
            room: 'Art Studio',
            type: 'activity' as const,
          },
        },
      },
      {
        timeSlot: '2:10 - 3:00',
        periods: {
          monday: {
            id: 'period-37',
            subject: 'Computer Science',
            teacher: { firstName: 'Ms.', lastName: 'Lee' },
            room: 'Computer Lab',
            type: 'regular' as const,
          },
          tuesday: {
            id: 'period-38',
            subject: 'Study Hall',
            teacher: { firstName: 'Ms.', lastName: 'Anderson' },
            room: 'Library',
            type: 'study_hall' as const,
          },
          wednesday: {
            id: 'period-39',
            subject: 'Library Period',
            teacher: { firstName: 'Ms.', lastName: 'Johnson' },
            room: 'Library',
            type: 'study_hall' as const,
          },
          thursday: {
            id: 'period-40',
            subject: 'Biology',
            teacher: { firstName: 'Ms.', lastName: 'Garcia' },
            room: 'Lab 301',
            type: 'regular' as const,
          },
          friday: {
            id: 'period-41',
            subject: 'Assembly',
            teacher: { firstName: 'Ms.', lastName: 'Principal' },
            room: 'Main Hall',
            type: 'activity' as const,
          },
          saturday: {
            id: 'period-42',
            subject: 'Counseling Session',
            teacher: { firstName: 'Ms.', lastName: 'Garcia' },
            room: '105',
            type: 'study_hall' as const,
          },
        },
      },
    ],
  },
};

export const mockRootProps = {
  classId: 'class-1',
  sectionId: 'section-1',
  initialGrade: 'Grade 10',
  initialSection: 'A',
};
